version: 0.0
Resources:
  - MyFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "MyFunction"
        Alias: "MyFunctionAlias"
        # CurrentVersion: "1"
        # TargetVersion: "2"
